### PR TITLE
Add simple keyword filtering

### PR DESCRIPTION
**Pull request by techxplorer**
Many thanks for developing this plugin. It was nearly exactly what I needed. The only thing missing was the ability to filter the list of tweets by a keyword. 

I've added a simple keyword check to the import script, I've tried to maintain the same code style. 

I hope you consider including this in a future release.

### CODE REVIEW

**Comment by ozh** [comment]
Not sure I get what this does, can you elaborate a bit? What would be exactly "filter the list of tweets by a keyword"?

**Comment by techxplorer** [comment]
My understanding is that your primary use case for the plugin is to archive **all** tweets from the Twitter account into WordPress. My use case was for only **some** of the tweets to be archived. Specifically those that contained a specific hashtag. 

So the changes are designed to allow filtering of tweets by keyword. If the tweet contains one of the defined keywords it gets archived. Conversely, if it doesn't contain the keyword then it isn't archived. 

I imagine it would be possible to add the filter to the twitter API call, however when changing someone else's code I try to make the minimal amount of changes. Does this help?

**Comment by ozh** [comment]
Oh, OK. This is out of the scope of this plugin, then, I don't want to add another option for this specific need. If more people need that feature though maybe the best option would be to add a hook to this plugin so a companion plugin could handle the filtering.

**Comment by techxplorer** [comment]
Thanks for taking the time to consider the pull request and for writing the plugin. It is greatly appreciated.

**Pull request closed without merging**
