### PR TITLE
Display multiple images if present.

### LINKED ISSUE #23: Only first attached image appears
A Twitter image link can contain up to four (I think) images. ozh-tweet-archiver only shows the first one. Is there a way to enable display of multiple images? Or can you point me at where in the code this could be fixed?

Example:
* ozh: http://gurunoia.lochan.org/tweets/2015/11/13/its-been-a-while-since-the-last-polmont-platform-extension-update-as-you-can-see-its-getting-close-to-finished-pic-twitter-comj1jwx8cscb/
* Twitter: https://twitter.com/kw217/statuses/665084868737507328

Thanks.

--KW 8-)

### PR DESCRIPTION
**Pull request by kw217**
Use extended_media instead of media (thanks
http://www.leancrew.com/all-this/2014/06/tweets-with-multiple-photos/). This means we can see multiple photos attached at once.

This resolves #23 .

### CODE REVIEW

**Comment by ozh** [comment]
Tested live ? Works ?

**Comment by kw217** [comment]
Yes - check the most recent tweet at http://gurunoia.lochan.org/tweets/ (or [permalink](http://gurunoia.lochan.org/tweets/2015/12/05/fascinating-watching-the-weather-go-by-ukstorm-pic-twitter-comlwx0rcvzju/) ).

**Comment by ozh** [comment]
Broken image links as far as I can tell :)

**Comment by kw217** [comment]
Works for me. Which links are broken?

**Comment by ozh** [comment]
Indeed. For some reason, my Firefox hides all images, while IE or Chrome show them OK. Maybe related to https/http mixing in a recent FF update. Thanks anyway!

**Comment by ozh** [comment]
While you're on images, if you could test this that would be super appreciated: https://github.com/ozh/ozh-tweet-archiver/pull/19

**Comment by kw217** [comment]
Thanks!

**Pull request merged**
