### PR TITLE
Adding json importer

### PR DESCRIPTION
**Pull request by danielfaulknor**
Import JSON files instead of CSV which means you don't have to touch the Twitter API. Makes importing many thousands of tweets exponentially faster

### CODE REVIEW

**Comment by ozh** [comment]
Where do you get the JSON from?

**Comment by danielfaulknor** [comment]
Twitter archive download 
You request at the bottom of https://twitter.com/settings/account

**Comment by ozh** [comment]
I thought you meant your file was made to read one .JSON archive, I see that instead it's reading all the .js files Twitter provides

The process is the same as my script with the .CSV, it doesnt use the Twitter API and as such it shouldn't be any faster or slower (reading data from .CSV or .JS is essentially the same)

I'm not going to include this in the plugin for the same reason as the other PR (too complicated for noobs == too many support requests) but I'll mention this script from the plugin page in case someone prefers using JSON over CSV data. Thanks for this

**Comment by ozh** [comment]
Mirrored here in case you delete your branch/fork : https://gist.github.com/ozh/f5deafcffd8d271bfa92

**Comment by danielfaulknor** [comment]
The difference in mine is I use ozh_ta_insert_tweets instead of ozh_ta_import_single_tweet which touches the API to get data for each tweet, as all data required is in the JSON and not the CSV

**Pull request closed without merging**
